name: fiqo CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    name: check
    steps:
      - uses: actions/checkout@v5

      - name: Check one editorconfig
        run: |
          if [ "$(find . -name '.editorconfig' | wc -l)" != "1" ]
          then
            exit 1
          fi

      - name: Install editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@v2
        with:
          version: v3.0.3

      - run: editorconfig-checker

  fiqo:
    needs:
      - check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fiqo-backend
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "24"
          distribution: "temurin"
          cache: maven

      - name: Build and Verify
        run: mvn -B -ntp verify

  fiqo-cli:
    needs:
      - check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fiqo-cli
    steps:
      - uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: "22"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint Check
        run: pnpm run lint

      - name: Build
        run: pnpm run build
