version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/fiqo-backend"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/fiqo-cli"
    schedule:
      interval: "daily"
